defaults:
    - _self_
    # - ex: aspec.enja.baseline.100k
    - ex: aspec.enja.nfr.labse.enh100k_to_jah2m.top8.archi7
    # - ex: debug2
    - out_dir:

do_train: True
do_eval: True
do_predict: True
